### ISSUE TITLE
cannot get module to import

### ISSUE THREAD

**Issue by simpert** [avinashsivaraman/awesome-react-calculator#1]
Hello I was interested in this module and I failed to use it in my project. I am using 16.x react and typescript project but the module will no import.

I wonder if it has anything to do with the 
```
 "peerDependencies": {
    "react": "15.x"
  },
```  
in the `package.json` file.

**Comment by avinashsivaraman** [comment]
Can you able to reproduce the bug in codesandbox and provide me the link to test ?
