### ISSUE TITLE
Does not work on mobile

### ISSUE THREAD

**Issue by JakeRuth** [avinashsivaraman/awesome-react-calculator#3]
Hey, this calculator is awesome! I'm not sure if it's maintained anymore but this doesn't work on mobile (at least on my pixel 4)

I am likely going to try to fix this so i may resolve my own request here... but this is a partial ping on ownership/active maintenance/push to the shared npm package

**Comment by avinashsivaraman** [comment]
It's working for me. Can you share what error you are getting when rendering the component ?

**Comment by JakeRuth** [comment]
> It's working for me. Can you share me the error you are getting when rendering the component ?

Hello :) thanks for the quick reply.

Apologies for not being more specific. It renders for me but when I click buttons none of the click events send to do anything

I am rendering this as a draggable component with another lib so I will poke around more with a simpler example to see if it's something else that blocks the blocks the events on my end (note this doesn't happen with desktop load mobile tender through chrome dev tools) 

It looks like this
![Screenshot_20210713-081153~2](https://user-images.githubusercontent.com/7349551/125449967-b7691c62-9d16-46b4-8682-66590892feda.png)

**Comment by avinashsivaraman** [comment]
Can you share the code snippet which you are using ? I suspect that draggable component which you are using might be doing something wrong. 

I tested with my [live demo link](https://csb-ncxvw.netlify.com/). It is working properly.

**Comment by JakeRuth** [comment]
> Can you share the code snippet which you are using ? I suspect that draggable component which you are using might be doing something wrong.
> 
> I tested with my [live demo link](https://csb-ncxvw.netlify.com/). It is working properly.

I agree. Sorry for the noise here!
